// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5smU_JOFvvaePoYqRzVIddaiBcvB8ec',
    appId: '1:687550089448:web:03086d53331d04e6e6e15d',
    messagingSenderId: '687550089448',
    projectId: 'task-manager-9d8c5',
    authDomain: 'task-manager-9d8c5.firebaseapp.com',
    storageBucket: 'task-manager-9d8c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxK4161j9hUMMejV2XAniM6pPMfLtfyQE',
    appId: '1:687550089448:android:6919b057947f3706e6e15d',
    messagingSenderId: '687550089448',
    projectId: 'task-manager-9d8c5',
    storageBucket: 'task-manager-9d8c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUq-QzcSyn2AXuReS47rERrs3K2OKoLM',
    appId: '1:687550089448:ios:fed5ac415d54af5ce6e15d',
    messagingSenderId: '687550089448',
    projectId: 'task-manager-9d8c5',
    storageBucket: 'task-manager-9d8c5.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
}
